# Generated by Django 4.1.1 on 2023-01-13 07:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=6, verbose_name='Valstybinis_NR')),
                ('vin_kodas', models.TextField(help_text='Įveskite automobilio VIN kodą.', max_length=17, verbose_name='VIN_kodas')),
                ('klientas', models.TextField(help_text='Įveskite automobilio savininką.', max_length=25, verbose_name='Klientas')),
            ],
        ),
        migrations.CreateModel(
            name='AutomobilisModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.CharField(max_length=20, verbose_name='Metai')),
                ('marke', models.CharField(max_length=20, verbose_name='Markė')),
                ('modelis', models.CharField(max_length=20, verbose_name='Modelis')),
                ('variklis', models.CharField(max_length=20, verbose_name='Variklis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugą.', max_length=200, verbose_name='Paslauga')),
                ('kaina', models.FloatField(help_text='Įveskite paslaugos kainą.', max_length=10, verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus užsakymo ID', primary_key=True, serialize=False)),
                ('atsiemimo_data', models.DateField(verbose_name='Atsiėmimo data')),
                ('suma', models.FloatField(help_text='Įveskite bendrą paslaugų sumą.', max_length=10, verbose_name='Suma')),
                ('automobilis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.automobilis')),
            ],
            options={
                'ordering': ['atsiemimo_data'],
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(help_text='Įveskite paslaugų kiekį.', max_length=200, verbose_name='Kiekis')),
                ('kaina', models.CharField(help_text='Įveskite paslaugų kainą.', max_length=200, verbose_name='Kaina')),
                ('paslauga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.paslauga')),
                ('uzsakymas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.uzsakymas')),
            ],
        ),
        migrations.AddField(
            model_name='automobilis',
            name='automobilis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.automobilismodelis'),
        ),
    ]
